apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./resources/secrets/serviceaccount/serviceaccount.yaml
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: gateway-license
  files:
  - ./resources/secrets/license/license.xml
- name: gateway-secret
  env: ./resources/secrets/gateway/secret.env
- name: graphman-encryption-secret
  env: ./resources/secrets/gateway/graphman-encryption-secret.env

# Create a secret for the Ingress Resource
# Uncomment this section to create your own certificate for the ingress controller.
- name: gatewaytls
  files:
  - ./resources/secrets/tls/tls.crt
  - ./resources/secrets/tls/tls.key
  type: "kubernetes.io/tls"