apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./resources/serviceaccount/serviceaccount.yaml
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: gateway-license
  files:
  - ./settings/secrets/license/license.xml
- name: gateway-secret
  env: ./settings/secrets/gateway/secret.env
- name: graphman-encryption-secret
  env: ./settings/secrets/gateway/graphman-encryption-secret.env

